### ISSUE TITLE
Need Clarification on README instructions for generating javadocs

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-javadocs#2]
Hi @REAS,

I was going through the README and it suggests copying "three generated folders" to the `processing-javadocs` repo. From what I can see in the `processing-javadocs` repo here, I am assuming this refers to the `javadoc`, `libraries`, and `everything` folders. Could you confirm if this is correct?

Additionally, when I run `ant doc` in the `processing4` repository, it seems to only create the `javadoc` directory. Could you help me understand why this is the case? Thanks in advance!

**Comment by benfry** [comment]
Made a few edits so that this will build properly.

Looks like we also need to change all the `<h3>` entries (usually for the “Advanced” section) to `<h2>` in the reference, since JavaDoc gets upset about jumping to `<h3>` without first doing `<h2>`.
